### ISSUE TITLE
Issue with the grade so far function

### ISSUE THREAD

**Issue by anonymous513** [CodeGrade/bottlenose#111]
![grades_li](https://user-images.githubusercontent.com/44079081/46846970-095f9f80-cdb0-11e8-9df1-50ca83cdf9f2.jpg)

Maybe its my imagination but the grade so far function doesn't seem to function as intended, looks like it included ungraded items that are not past their deadline? I also have very little Github experience so I'm sure there are better ways to go about this but oh well

**Comment by blerner** [comment]
Thanks for reporting :)  This is working as intended, but to be fair, Grade so far is a tricky estimate.  If you have an assignment that you haven't submitted to yet, but whose deadline is in the future, it assumes you'll get a zero on it (because you haven't submitted yet, we assume that you just won't actually submit).  If you have an assignment that you've submitted to that isn't graded yet, it assumes you'll get 100% (because we're optimistic).

**Comment by johnc1231** [comment]
Why not just have grade so far be based solely on graded and published things?

**Comment by blerner** [comment]
We tried that, your year of OOD.  No one liked it, because it didn't update in response to submitted homeworks, and people complained that "it was broken".
