### ISSUE TITLE
Admin's are able to edit/accept/deny student registrations 

### ISSUE THREAD

**Issue by grobalex** [CodeGrade/bottlenose#142]
Logged in as an Admin user, the user can view any courses currently available on the server. When navigating to a course that the user is not enrolled in and then going to registrations the user can accept / deny pending course registrations and edit current student registrations but **cannot** edit staff registrations.  

In registrations_controller#index line 18-19 there is a check to see if the current user is an admin and then mark their role as professor.

In registrations_controller#bulk_edit we can also add another elseif to check if: current_user.registration_for(@course) and if not show an error message.

**Comment by blerner** [comment]
Valid bug, irrelevant solution :)  The reason for lines 18-19 is because rendering `registrations#index` requires knowing the role of the `current_user`, to tailor the rendering appropriately.  Checking for `current_user.registration_for(@course)` ought to be done once-and-for-all at the top of the file, in the `before_action`s section.  

We already have a `find_registration` method, but it gets ignored most of the time: this is because it's attempting to find a registration with a given id; that value doesn't exist on the pages for which this check is ignored.  We also check, on the other pages, that we have a registered user for the course (via `require_registered_user` and sets the `@registration` field accordingly.  But that function (defined in `ApplicationController`) deliberately passes when the current user is an admin, and leaves `@registration = nil`.  So the right thing to do is to 
- eliminate `current_user.registration_for(@course)&.role` in favor of `@registration&.role`
- change the line entirely, to `@cur_role = (current_user_site_admin? ? "professor" : @registration&.role)`, which allows admins broader authority.  This permission already exists in `RegistrationsController#bulk_update`, so it's consistent.

**Comment by kylesferrazza** [comment]
This is closed by https://github.com/blerner/bottlenose/pull/19.
