### ISSUE TITLE
Registration tagging

### ISSUE THREAD

**Issue by NatTuck** [CodeGrade/bottlenose#34]
We want to have a mechanism for marking students by, e.g., lab section.

This may replace the current course section system, or be added in addition to it.

**Comment by blerner** [comment]
I'm working on a revision right now that adds a type field to each section (enumerated: Lecture, Lab, Recitation, Online), and other section types might follow.  I now have a 1->many table connecting registrations to sections.  I'm doing it this way rather than via free-form tags because it was easier to schematize and confirm that I was doing it correctly.  Most of the UI work is done, and tests are passing.  I want to stabilize it a bit, and fix up the Randomize Teams page to take advantage of the new by-section-type machinery (so that it tries to randomize times only within labs), then I'll open a PR.

**Comment by blerner** [comment]
This is merged in PR #77
