### ISSUE TITLE
Change `Meeting Time` Type from `String` to `Duration`(time)

### ISSUE THREAD

**Issue by xingyif** [CodeGrade/bottlenose#59]
Currently, the user can input ANYTHING into the meeting time text box under `Sections` Tab, when creating a class. The user should only be allowed to input the time of section, not other types.

This is the current view:

![screen shot 2017-05-24 at 17 24 11](https://cloud.githubusercontent.com/assets/15064985/26426745/021e875e-40a8-11e7-961e-92711bb64bef.png)

----------------------------

This is what the `Meeting Time` should look like: (except the `Start/End Date` will be `Start/End Time`)

![screen shot 2017-05-24 at 17 37 04](https://cloud.githubusercontent.com/assets/15064985/26426744/02151d72-40a8-11e7-8d46-b0aa50ed6df3.png)

**Comment by blerner** [comment]
I'm not sure I want to do this, actually: it's entirely possible a section might have a time of "Online"...

**Comment by xingyif** [comment]
It should at least have some form of input restriction. Currently you can put ANYTHING as the meeting time.
The meeting time doesn't have to be a required field. If CCIS offers an online section, the instructor has the option not to input the meeting time.

**Comment by blerner** [comment]
But then you'd have sections appearing in bottlenose with no description whatsoever.  I don't think we want that

**Comment by xingyif** [comment]
how does changing the meetingTime type cause "sections appearing in bottlenose with no description"

**Comment by blerner** [comment]
"The instructor has the option not to input the meeting time".  Think about what you're suggesting for a bit: we routinely have multiple sections at the same time in Fundies, we may well have sections that don't have any set time, soon (I'm thinking in particular about labs, in semesters coming soon), and we even routinely have two sections at the same time with the same instructor (4000- and 6000-level courses).  So simply having "meeting time" as a strictly schematized start time/end time pair (note: *not* a duration, because "1 hour 40 minutes" is not a useful description of when a section is!) isn't enough to distinguish the sections.  Think of this field rather as a description, not a time block.  This is a case where we simply don't *need* the schematization, the flexibility of the string field is better for us, and we can easily tweak the UI to prompt the instructor to describe the section as `(Hint: "Start time -- end time in room ###")` or something similar.  Since this field is controlled entirely by the professor, they're not going to write something juvenile like "haha not a time"...
