### ISSUE TITLE
[cs3500] Only displaying 3 (not all) failed tests results for students

### ISSUE THREAD

**Issue by xingyif** [CodeGrade/bottlenose#60]
<img width="1024" alt="2017-05-25 5 45 16" src="https://cloud.githubusercontent.com/assets/15064985/26472004/39c6efaa-4172-11e7-8569-7e615938089e.png">

<img width="1024" alt="2017-05-25 5 45 24" src="https://cloud.githubusercontent.com/assets/15064985/26472002/387aad44-4172-11e7-977d-a3c88d0f6fcf.png">

**Comment by blerner** [comment]
This is deliberate.  I do *not* want to show Fundies students every mistake they made: I don't want them to think that Bottlenose is their oracular debugger.  This could be made more general, though: instead of showing 3 as a hard-coded limit, this could be configured by the instructor.  But that requires more fine-grained control than we have right now, and requires Nat's reworking of the sandboxed graders, first.
